### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by danieladeyemo**
added __repr__s to model classes. Left in a couple of comments.

### CODE REVIEW

**Comment by nnamdiib** [comment]
Why you making the return self codes .upper() ?

Why did you delete abbrv ?

I deleting it will break something along the line. You said you don't have django, so you can't clone and test it locally?

**Comment by danieladeyemo** [comment]
About abbrv I commented it out asking if it was necessary since we don't use abbrvs to refer to majors in CU. They aren't standard or consistent across people's usage of them.

Self.codes.upper makes sure things like csc121 would be rendered as CSC121 at all times.

We have to work on the dB on another branch to avoid breaking stuff. Breaking stuff shouldn't be our concern now since we are still figuring out the most efficient design for the database. Every thing else can be made to align when the models are in stable mode.

**Comment by nnamdiib** [comment]
commenting out abbrv affects nothing in this version i uploaded, but at some point is was how the courses ere retrieved. I think that's why I left it. Anyhow you deleted the 'mon', 'tue' attributes in the courses models. Check again.

**Comment by danieladeyemo** [comment]
Oh, how did that happen. I'll fix that.

**Comment by danieladeyemo** [comment]
Nope, all the weekdays are still there. Maybe because you are viewing the file in diff mode. That way you are only seeing the part of the code that was changed. In this case I predict you can only see Thu and Fri.

View the file without the compare mode.

**Comment by danieladeyemo** [comment]
So abbrv is not how we would like to retrieve majors. We want to access it by Major name which we of course would hard-code.  For consistency sake.

Can I be merged now?

**Comment by danieladeyemo** [comment]
I cloned it to my laptop without my proposed changes (the original version). It isn't launching with this error:

`django.db.utils.OperationalError: no such table: new_studentable_level`

**Comment by danieladeyemo** [comment]
are there any dependencies I should be aware of?

**Comment by nnamdiib** [comment]
dependencies, I'm guessing you don't have the database installed. So it wion't work. 

Do you have the database?

**Comment by danieladeyemo** [comment]
Where do you get the database from?

**Pull request merged**
